"""
Base strategy interface for trading strategies.

Defines the contract that all trading strategies must implement.
"""

from abc import ABC, abstractmethod
from typing import List, Any, Dict
from dataclasses import dataclass


@dataclass
class StrategySignal:
    """Trading signal generated by a strategy."""

    should_buy: bool
    should_sell: bool
    confidence: float = 1.0
    metadata: Dict[str, Any] = None

    def __post_init__(self) -> None:
        """Initialize metadata if None."""
        if self.metadata is None:
            self.metadata = {}


class BaseStrategy(ABC):
    """Abstract base class for trading strategies."""

    def __init__(self, name: str):
        """
        Initialize strategy.

        Args:
            name: Strategy name identifier
        """
        self.name = name

    @abstractmethod
    def analyze(self, ohlcv: List[List[Any]]) -> StrategySignal:
        """
        Analyze market data and generate trading signal.

        Args:
            ohlcv: OHLCV candlestick data
                  [timestamp, open, high, low, close, volume]

        Returns:
            StrategySignal with buy/sell recommendations

        Raises:
            ValueError: If ohlcv data is invalid or insufficient
        """
        pass

    @abstractmethod
    def get_required_candles(self) -> int:
        """
        Get minimum number of candles required for analysis.

        Returns:
            Minimum number of candles needed
        """
        pass

    def validate_data(self, ohlcv: List[List[Any]]) -> None:
        """
        Validate OHLCV data before analysis.

        Args:
            ohlcv: OHLCV candlestick data

        Raises:
            ValueError: If data is invalid or insufficient
        """
        if not ohlcv:
            raise ValueError("OHLCV data is empty")

        required = self.get_required_candles()
        if len(ohlcv) < required:
            raise ValueError(
                f"Insufficient data: need {required} candles, "
                f"got {len(ohlcv)}"
            )
